# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy NodeJS app
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: root
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          mkdir -p ~/my-express-app/ # create a new folder
          cd ~/my-express-app/ # navigate into the folder
          git clone https://github.com/Bradleykingz/github-actions-tutorial app # clone the repo into the 'app' folder
          cd github-actions-tutorial # navigate into the repo
          npm install # install dependencies 
          pm2 start app.js # start as a background service.
